//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Top10Svc {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Top10Svc.ITextAnalytics")]
    public interface ITextAnalytics {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITextAnalytics/Top10ContentWords", ReplyAction="http://tempuri.org/ITextAnalytics/Top10ContentWordsResponse")]
        string[] Top10ContentWords(string inputOrUrl);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITextAnalytics/Top10ContentWords", ReplyAction="http://tempuri.org/ITextAnalytics/Top10ContentWordsResponse")]
        System.Threading.Tasks.Task<string[]> Top10ContentWordsAsync(string inputOrUrl);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITextAnalyticsChannel : WebApplication1.Top10Svc.ITextAnalytics, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TextAnalyticsClient : System.ServiceModel.ClientBase<WebApplication1.Top10Svc.ITextAnalytics>, WebApplication1.Top10Svc.ITextAnalytics {
        
        public TextAnalyticsClient() {
        }
        
        public TextAnalyticsClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TextAnalyticsClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TextAnalyticsClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TextAnalyticsClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string[] Top10ContentWords(string inputOrUrl) {
            return base.Channel.Top10ContentWords(inputOrUrl);
        }
        
        public System.Threading.Tasks.Task<string[]> Top10ContentWordsAsync(string inputOrUrl) {
            return base.Channel.Top10ContentWordsAsync(inputOrUrl);
        }
    }
}
