//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.PokerBotServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BotRequest", Namespace="http://schemas.datacontract.org/2004/07/PokerBot")]
    [System.SerializableAttribute()]
    public partial class BotRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string GameStateJsonField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string GameStateJson {
            get {
                return this.GameStateJsonField;
            }
            set {
                if ((object.ReferenceEquals(this.GameStateJsonField, value) != true)) {
                    this.GameStateJsonField = value;
                    this.RaisePropertyChanged("GameStateJson");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BotDecisionResponse", Namespace="http://schemas.datacontract.org/2004/07/PokerBot")]
    [System.SerializableAttribute()]
    public partial class BotDecisionResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ActionTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RawModelResponseField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ActionType {
            get {
                return this.ActionTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.ActionTypeField, value) != true)) {
                    this.ActionTypeField = value;
                    this.RaisePropertyChanged("ActionType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Amount {
            get {
                return this.AmountField;
            }
            set {
                if ((this.AmountField.Equals(value) != true)) {
                    this.AmountField = value;
                    this.RaisePropertyChanged("Amount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RawModelResponse {
            get {
                return this.RawModelResponseField;
            }
            set {
                if ((object.ReferenceEquals(this.RawModelResponseField, value) != true)) {
                    this.RawModelResponseField = value;
                    this.RaisePropertyChanged("RawModelResponse");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PokerBotServiceReference.IPokerBotService")]
    public interface IPokerBotService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPokerBotService/GetBotDecision", ReplyAction="http://tempuri.org/IPokerBotService/GetBotDecisionResponse")]
        WebApplication1.PokerBotServiceReference.BotDecisionResponse GetBotDecision(WebApplication1.PokerBotServiceReference.BotRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPokerBotService/GetBotDecision", ReplyAction="http://tempuri.org/IPokerBotService/GetBotDecisionResponse")]
        System.Threading.Tasks.Task<WebApplication1.PokerBotServiceReference.BotDecisionResponse> GetBotDecisionAsync(WebApplication1.PokerBotServiceReference.BotRequest request);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPokerBotServiceChannel : WebApplication1.PokerBotServiceReference.IPokerBotService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PokerBotServiceClient : System.ServiceModel.ClientBase<WebApplication1.PokerBotServiceReference.IPokerBotService>, WebApplication1.PokerBotServiceReference.IPokerBotService {
        
        public PokerBotServiceClient() {
        }
        
        public PokerBotServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PokerBotServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PokerBotServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PokerBotServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WebApplication1.PokerBotServiceReference.BotDecisionResponse GetBotDecision(WebApplication1.PokerBotServiceReference.BotRequest request) {
            return base.Channel.GetBotDecision(request);
        }
        
        public System.Threading.Tasks.Task<WebApplication1.PokerBotServiceReference.BotDecisionResponse> GetBotDecisionAsync(WebApplication1.PokerBotServiceReference.BotRequest request) {
            return base.Channel.GetBotDecisionAsync(request);
        }
    }
}
